frr version 8.4_git
frr defaults traditional
hostname 6dcbf2b7e59f
domainname localdomain
log stdout
no ipv6 forwarding
service integrated-vtysh-config
!
router bgp 2
 no bgp ebgp-requires-policy
 neighbor 172.16.12.11 remote-as 1
 neighbor 172.16.23.3 remote-as 3
exit
!
