#!/usr/bin/env python3
"""R-2B VRP-aware verifier smoke with incident component audit.

This script consumes the aligned RPKI/VRP lookup generated by R-2B-P0b and
joins it back to S3-D incident queues. It intentionally does not modify any
legacy detector output and does not produce confirmed attack/benign labels.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

import pandas as pd


R1_VERDICTS = {
    "strongly_supported_suspicious",
    "evidence_supported_suspicious",
    "evidence_conflict",
    "evidence_insufficient",
    "external_evidence_unavailable",
    "background_like_but_unconfirmed",
    "stale_evidence_only",
    "abstain",
}

RPKI_STATUSES = ["valid", "invalid_asn", "invalid_length", "unknown", "unavailable"]
INVALID_STATUSES = {"invalid_asn", "invalid_length"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--run-date", default="2024-04-16")
    parser.add_argument("--rpki-lookup-file", required=True)
    parser.add_argument("--targets-file", required=True)
    parser.add_argument("--s3d-output-dir", required=True)
    parser.add_argument("--r2a-output-dir", default="")
    parser.add_argument("--incident-tickets-file", required=True)
    parser.add_argument("--incident-membership-file", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--sample-rows", type=int, default=0)
    parser.add_argument("--full-run", action="store_true")
    return parser.parse_args()


def read_parquet_required(path: str | Path, columns: list[str] | None = None) -> pd.DataFrame:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"required input missing: {p}")
    return pd.read_parquet(p, columns=columns)


def read_json(path: str | Path) -> dict[str, Any]:
    p = Path(path)
    if not p.exists():
        return {}
    with p.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, sort_keys=True, ensure_ascii=False)
        f.write("\n")


def normalize_prefix(value: Any) -> str:
    if pd.isna(value):
        return ""
    return str(value).strip()


def normalize_asn(value: Any) -> str:
    if pd.isna(value):
        return ""
    text = str(value).strip()
    if not text or text.upper() in {"NA", "NAN", "NONE", "NULL"}:
        return ""
    if text.upper().startswith("AS"):
        text = text[2:]
    try:
        return str(int(float(text)))
    except ValueError:
        return text


def safe_float(value: Any, default: float = 0.0) -> float:
    if pd.isna(value):
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def distribution(series: pd.Series) -> dict[str, int]:
    if series.empty:
        return {}
    return {str(k): int(v) for k, v in series.fillna("NA").value_counts().sort_index().items()}


def prefixed_distribution(df: pd.DataFrame, cols: list[str]) -> dict[str, int]:
    out: dict[str, int] = {}
    for col in cols:
        if col in df.columns:
            for key, val in distribution(df[col]).items():
                out[f"{col}:{key}"] = val
    return out


def entropy_from_counts(counts: list[float]) -> float:
    total = sum(c for c in counts if c > 0)
    if total <= 0:
        return 0.0
    entropy = 0.0
    for count in counts:
        if count <= 0:
            continue
        p = count / total
        entropy -= p * math.log(p, 2)
    return float(entropy)


def first_existing_columns(path: Path, desired: list[str]) -> list[str]:
    # pandas does not expose a cheap schema-only API consistently across engines,
    # so this helper reads no data via pyarrow when available.
    import pyarrow.parquet as pq

    schema = pq.ParquetFile(path).schema_arrow
    cols = set(schema.names)
    return [c for c in desired if c in cols]


def load_incident_base(args: argparse.Namespace, warnings: list[str]) -> pd.DataFrame:
    s3d_path = Path(args.s3d_output_dir) / "s3d_incident_verification_queue.parquet"
    s3d = read_parquet_required(s3d_path)
    if "incident_id" not in s3d.columns:
        raise ValueError("S3-D queue missing incident_id")

    tickets = read_parquet_required(args.incident_tickets_file)
    ticket_cols = [
        "incident_id",
        "run_id",
        "incident_priority",
        "incident_start",
        "incident_end",
        "incident_duration_sec",
        "dominant_prefix",
        "dominant_origin_as",
        "incident_score",
        "incident_confidence",
        "collector_union_count",
        "affected_prefix_count",
        "origin_as_count",
    ]
    ticket_cols = [c for c in ticket_cols if c in tickets.columns]
    tickets = tickets[ticket_cols].copy()
    rename = {
        "incident_priority": "legacy_incident_priority",
        "incident_score": "ticket_incident_score",
        "incident_confidence": "ticket_incident_confidence",
        "dominant_prefix": "ticket_dominant_prefix",
        "dominant_origin_as": "ticket_dominant_origin_as",
    }
    tickets = tickets.rename(columns={k: v for k, v in rename.items() if k in tickets.columns})

    base = s3d.merge(tickets, on="incident_id", how="left", suffixes=("", "_ticket"))

    if "run_id" not in base.columns:
        base["run_id"] = args.run_id
    base["run_id"] = base["run_id"].fillna(args.run_id)

    if args.sample_rows and not args.full_run:
        base = base.head(args.sample_rows).copy()
        warnings.append(f"sample mode processed first {len(base)} incidents from S3-D queue")

    for col in ["member_count", "high_count", "needs_count", "incident_score", "incident_confidence"]:
        if col not in base.columns:
            fallback = "ticket_" + col
            if fallback in base.columns:
                base[col] = base[fallback]
            else:
                base[col] = 0
                warnings.append(f"missing incident field filled with 0: {col}")

    if "calibrated_incident_priority" not in base.columns:
        if "legacy_incident_priority" in base.columns:
            base["calibrated_incident_priority"] = base["legacy_incident_priority"]
        else:
            base["calibrated_incident_priority"] = "NA"
            warnings.append("missing calibrated_incident_priority; filled with NA")

    if "original_incident_priority" not in base.columns:
        base["original_incident_priority"] = base.get("legacy_incident_priority", "NA")

    if "dominant_prefix" not in base.columns:
        base["dominant_prefix"] = base.get("ticket_dominant_prefix", "")
    if "dominant_origin_as" not in base.columns:
        base["dominant_origin_as"] = base.get("ticket_dominant_origin_as", "")

    for col in ["verification_queue", "family", "dominant_reason_signature"]:
        if col not in base.columns:
            base[col] = "NA"
            warnings.append(f"missing incident field filled with NA: {col}")

    return base


def load_rpki_lookup(path: str | Path, warnings: list[str]) -> tuple[pd.DataFrame, pd.DataFrame]:
    lookup = read_parquet_required(path)
    required = ["incident_id", "lookup_prefix", "lookup_origin_as", "rpki_status", "rpki_evidence_state", "target_id"]
    missing = [c for c in required if c not in lookup.columns]
    if missing:
        raise ValueError(f"RPKI lookup missing required columns: {missing}")

    lookup = lookup.copy()
    lookup["lookup_prefix_norm"] = lookup["lookup_prefix"].map(normalize_prefix)
    lookup["lookup_origin_as_norm"] = lookup["lookup_origin_as"].map(normalize_asn)

    incident_lookup = lookup[
        [
            "incident_id",
            "target_id",
            "rpki_status",
            "rpki_evidence_state",
            "rpki_lookup_note",
            "aligned_to_run_date",
            "cache_snapshot_date",
        ]
        if "rpki_lookup_note" in lookup.columns
        else ["incident_id", "target_id", "rpki_status", "rpki_evidence_state"]
    ].copy()
    incident_lookup = incident_lookup.rename(
        columns={
            "target_id": "dominant_pair_target_id",
            "rpki_status": "dominant_pair_rpki_status",
            "rpki_evidence_state": "dominant_pair_rpki_evidence_state",
            "rpki_lookup_note": "dominant_pair_rpki_lookup_note",
        }
    )
    incident_lookup = incident_lookup.drop_duplicates("incident_id", keep="first")

    pair_cols = [
        "lookup_prefix_norm",
        "lookup_origin_as_norm",
        "rpki_status",
        "rpki_evidence_state",
    ]
    pair_lookup = lookup[pair_cols].drop_duplicates().copy()
    conflict_pairs = pair_lookup.groupby(["lookup_prefix_norm", "lookup_origin_as_norm"])["rpki_status"].nunique()
    conflict_count = int((conflict_pairs > 1).sum())
    if conflict_count:
        warnings.append(f"RPKI pair lookup has {conflict_count} prefix-origin pairs with inconsistent statuses; first status is used")
    pair_lookup = pair_lookup.drop_duplicates(["lookup_prefix_norm", "lookup_origin_as_norm"], keep="first")
    pair_lookup = pair_lookup.rename(
        columns={
            "lookup_prefix_norm": "member_prefix_norm",
            "lookup_origin_as_norm": "member_origin_as_norm",
            "rpki_status": "member_rpki_status",
            "rpki_evidence_state": "member_rpki_evidence_state",
        }
    )
    return incident_lookup, pair_lookup


def component_audit(
    args: argparse.Namespace,
    base: pd.DataFrame,
    pair_lookup: pd.DataFrame,
    warnings: list[str],
) -> pd.DataFrame:
    membership_path = Path(args.incident_membership_file)
    wanted = ["incident_id", "prefix", "origin_as_norm", "final_alert_label"]
    cols = first_existing_columns(membership_path, wanted)
    for col in ["incident_id", "prefix", "origin_as_norm"]:
        if col not in cols:
            raise ValueError(f"incident_membership missing required column: {col}")

    membership = read_parquet_required(membership_path, columns=cols)
    incident_ids = set(base["incident_id"].astype(str))
    membership["incident_id"] = membership["incident_id"].astype(str)
    membership = membership[membership["incident_id"].isin(incident_ids)].copy()
    if membership.empty:
        warnings.append("incident membership join returned no rows for processed incidents")

    membership["member_prefix_norm"] = membership["prefix"].map(normalize_prefix)
    membership["member_origin_as_norm"] = membership["origin_as_norm"].map(normalize_asn)

    group_cols = ["incident_id", "member_prefix_norm", "member_origin_as_norm"]
    pair_counts = membership.groupby(group_cols, dropna=False).size().reset_index(name="member_pair_count")

    member_lookup = build_member_pair_lookup_from_vrp(args, pair_counts, warnings)
    if not member_lookup.empty:
        pair_lookup = member_lookup

    pair_counts = pair_counts.merge(
        pair_lookup,
        on=["member_prefix_norm", "member_origin_as_norm"],
        how="left",
    )
    pair_counts["member_rpki_status"] = pair_counts["member_rpki_status"].fillna("unavailable")
    pair_counts["member_rpki_evidence_state"] = pair_counts["member_rpki_evidence_state"].fillna("unavailable")

    status_counts = (
        pair_counts.pivot_table(
            index="incident_id",
            columns="member_rpki_status",
            values="member_pair_count",
            aggfunc="sum",
            fill_value=0,
        )
        .reset_index()
        .copy()
    )
    for status in RPKI_STATUSES:
        if status not in status_counts.columns:
            status_counts[status] = 0
    status_counts = status_counts.rename(
        columns={
            "valid": "rpki_valid_member_count",
            "invalid_asn": "rpki_invalid_asn_member_count",
            "invalid_length": "rpki_invalid_length_member_count",
            "unknown": "rpki_unknown_member_count",
            "unavailable": "rpki_unavailable_member_count",
        }
    )

    unique_counts = (
        pair_counts.groupby("incident_id")
        .agg(
            prefix_origin_unique_count=("member_prefix_norm", "size"),
            rpki_status_unique_count=("member_rpki_status", "nunique"),
        )
        .reset_index()
    )

    dominant = base[["incident_id", "dominant_prefix", "dominant_origin_as"]].copy()
    dominant["dominant_prefix_norm"] = dominant["dominant_prefix"].map(normalize_prefix)
    dominant["dominant_origin_as_norm"] = dominant["dominant_origin_as"].map(normalize_asn)

    dominant_counts = pair_counts.merge(
        dominant[["incident_id", "dominant_prefix_norm", "dominant_origin_as_norm"]],
        on="incident_id",
        how="left",
    )
    dominant_counts["is_dominant_pair"] = (
        (dominant_counts["member_prefix_norm"] == dominant_counts["dominant_prefix_norm"])
        & (dominant_counts["member_origin_as_norm"] == dominant_counts["dominant_origin_as_norm"])
    )
    dominant_counts["dominant_member_count_part"] = dominant_counts["member_pair_count"].where(
        dominant_counts["is_dominant_pair"], 0
    )
    dominant_counts["dominant_invalid_count_part"] = dominant_counts["member_pair_count"].where(
        dominant_counts["is_dominant_pair"] & dominant_counts["member_rpki_status"].isin(INVALID_STATUSES), 0
    )
    dominant_agg = (
        dominant_counts.groupby("incident_id")
        .agg(
            dominant_prefix_origin_member_count=("dominant_member_count_part", "sum"),
            dominant_invalid_member_count=("dominant_invalid_count_part", "sum"),
        )
        .reset_index()
    )

    out = base[["incident_id", "member_count"]].copy()
    out = out.merge(status_counts, on="incident_id", how="left")
    out = out.merge(unique_counts, on="incident_id", how="left")
    out = out.merge(dominant_agg, on="incident_id", how="left")

    numeric_cols = [c for c in out.columns if c != "incident_id"]
    out[numeric_cols] = out[numeric_cols].fillna(0)

    out["rpki_invalid_total_count"] = out["rpki_invalid_asn_member_count"] + out["rpki_invalid_length_member_count"]
    denominator = out["member_count"].where(out["member_count"] > 0, 1)
    out["rpki_valid_share"] = out["rpki_valid_member_count"] / denominator
    out["rpki_invalid_share"] = out["rpki_invalid_total_count"] / denominator
    out["rpki_unknown_share"] = out["rpki_unknown_member_count"] / denominator
    out["rpki_unavailable_share"] = out["rpki_unavailable_member_count"] / denominator
    out["dominant_prefix_origin_share"] = out["dominant_prefix_origin_member_count"] / denominator

    invalid_total_den = out["rpki_invalid_total_count"].where(out["rpki_invalid_total_count"] > 0, 1)
    out["invalid_core_share"] = out["dominant_invalid_member_count"] / invalid_total_den
    out["invalid_edge_share"] = (out["rpki_invalid_total_count"] - out["dominant_invalid_member_count"]).clip(lower=0) / denominator
    out["suspicious_component_member_count"] = out["rpki_invalid_total_count"]
    out["suspicious_component_share"] = out["rpki_invalid_share"]
    out["rpki_status_entropy"] = out.apply(
        lambda row: entropy_from_counts(
            [
                row["rpki_valid_member_count"],
                row["rpki_invalid_asn_member_count"],
                row["rpki_invalid_length_member_count"],
                row["rpki_unknown_member_count"],
                row["rpki_unavailable_member_count"],
            ]
        ),
        axis=1,
    )
    out["mixed_rpki_status_flag"] = out["rpki_status_unique_count"] >= 2

    out["dominant_prefix_origin"] = (
        dominant["dominant_prefix_norm"].fillna("") + "|" + dominant["dominant_origin_as_norm"].fillna("")
    ).values

    out["should_split_incident_flag"] = (
        ((out["prefix_origin_unique_count"] >= 50) & (out["dominant_prefix_origin_share"] < 0.50))
        | ((out["prefix_origin_unique_count"] >= 200) & (out["dominant_prefix_origin_share"] < 0.70))
        | ((out["rpki_status_entropy"] >= 1.20) & (out["dominant_prefix_origin_share"] < 0.70))
    )

    out["component_purity_class"] = out.apply(classify_component_purity, axis=1)
    return out


def build_member_pair_lookup_from_vrp(
    args: argparse.Namespace,
    pair_counts: pd.DataFrame,
    warnings: list[str],
) -> pd.DataFrame:
    """Lookup all unique member prefix-origin pairs when local aligned VRP cache exists."""
    vrp_path = Path("data") / "evidence" / "rpki" / f"vrp_{args.run_date}.parquet"
    metadata_path = Path("data") / "evidence" / "rpki" / f"vrp_{args.run_date}.metadata.json"
    if not vrp_path.exists():
        warnings.append(f"member-level VRP lookup fallback: local VRP cache not found at {vrp_path}")
        return pd.DataFrame()

    script_dir = Path(__file__).resolve().parent
    if str(script_dir) not in sys.path:
        sys.path.insert(0, str(script_dir))
    try:
        from run_r2b_p0b_materialize_vrp_cache import lookup_targets, normalize_lookup_output
    except Exception as exc:  # pragma: no cover - defensive import guard
        warnings.append(f"member-level VRP lookup fallback: could not import P0b lookup helpers: {exc}")
        return pd.DataFrame()

    unique_pairs = pair_counts[["member_prefix_norm", "member_origin_as_norm"]].drop_duplicates().copy()
    unique_pairs = unique_pairs.reset_index(drop=True)
    unique_pairs["target_id"] = [f"member_po_{i:09d}" for i in range(len(unique_pairs))]
    unique_pairs["incident_id"] = ""
    unique_pairs["lookup_prefix"] = unique_pairs["member_prefix_norm"]
    unique_pairs["lookup_origin_as"] = unique_pairs["member_origin_as_norm"]
    unique_pairs["incident_start"] = ""
    unique_pairs["incident_end"] = ""
    unique_pairs["key_quality"] = unique_pairs.apply(
        lambda row: "complete" if row["lookup_prefix"] and row["lookup_origin_as"] else "unusable",
        axis=1,
    )

    vrp = pd.read_parquet(vrp_path)
    metadata = read_json(metadata_path)
    lookup = lookup_targets(
        unique_pairs[
            [
                "target_id",
                "incident_id",
                "lookup_prefix",
                "lookup_origin_as",
                "incident_start",
                "incident_end",
                "key_quality",
            ]
        ],
        vrp,
        metadata,
        args,
    )
    lookup = normalize_lookup_output(lookup)
    member_lookup = lookup[["lookup_prefix", "lookup_origin_as", "rpki_status", "rpki_evidence_state"]].copy()
    member_lookup["member_prefix_norm"] = member_lookup["lookup_prefix"].map(normalize_prefix)
    member_lookup["member_origin_as_norm"] = member_lookup["lookup_origin_as"].map(normalize_asn)
    member_lookup = member_lookup.rename(
        columns={
            "rpki_status": "member_rpki_status",
            "rpki_evidence_state": "member_rpki_evidence_state",
        }
    )
    member_lookup = member_lookup[
        ["member_prefix_norm", "member_origin_as_norm", "member_rpki_status", "member_rpki_evidence_state"]
    ].drop_duplicates(["member_prefix_norm", "member_origin_as_norm"], keep="first")
    warnings.append(f"member-level VRP lookup used local aligned cache for {len(member_lookup)} unique prefix-origin pairs")
    return member_lookup


def classify_component_purity(row: pd.Series) -> str:
    total = safe_float(row.get("member_count"))
    if total <= 0:
        return "insufficient_component_signal"
    dominant_share = safe_float(row.get("dominant_prefix_origin_share"))
    invalid_share = safe_float(row.get("rpki_invalid_share"))
    valid_share = safe_float(row.get("rpki_valid_share"))
    unknown_share = safe_float(row.get("rpki_unknown_share"))
    invalid_core = safe_float(row.get("invalid_core_share"))
    entropy = safe_float(row.get("rpki_status_entropy"))
    unique_pairs = safe_float(row.get("prefix_origin_unique_count"))

    if bool(row.get("should_split_incident_flag")):
        return "highly_mixed_should_split"
    if invalid_share >= 0.05 and valid_share >= 0.20 and entropy >= 0.70:
        return "mixed_conflicting"
    if invalid_share >= 0.10 and invalid_core >= 0.60:
        return "mixed_but_core_suspicious"
    if dominant_share >= 0.90:
        return "pure_dominant"
    if dominant_share >= 0.70:
        return "mostly_dominant"
    if unique_pairs > 1 or unknown_share > 0.50:
        return "insufficient_component_signal"
    return "insufficient_component_signal"


def verdict_for_row(row: pd.Series) -> dict[str, Any]:
    queue = str(row.get("verification_queue", ""))
    priority = str(row.get("calibrated_incident_priority", ""))
    component_class = str(row.get("component_purity_class", ""))
    dominant_status = str(row.get("dominant_pair_rpki_status", "unavailable"))
    high_count = safe_float(row.get("high_count"))
    high_share = safe_float(row.get("high_share"), high_count / max(safe_float(row.get("member_count")), 1.0))
    collector_count = safe_float(row.get("collector_union_count"))
    invalid_count = safe_float(row.get("rpki_invalid_total_count"))
    invalid_share = safe_float(row.get("rpki_invalid_share"))
    valid_share = safe_float(row.get("rpki_valid_share"))
    unknown_share = safe_float(row.get("rpki_unknown_share"))
    unavailable_share = safe_float(row.get("rpki_unavailable_share"))
    invalid_core_share = safe_float(row.get("invalid_core_share"))
    should_split = bool(row.get("should_split_incident_flag"))
    monitor_trigger = (
        high_count > 0
        or queue in {"high_confidence_candidate", "patternB_path_abnormal_verification", "gate_evidence_weak_case"}
        or priority in {"P1_high", "P2_review"}
    )
    strong_monitor_trigger = high_count > 0 or queue in {
        "high_confidence_candidate",
        "patternB_path_abnormal_verification",
    }

    conflict_reason = ""
    abstain_reason = ""
    confidence_cap_reason = "default evidence cap"
    evidence_summary = (
        f"monitor_trigger={monitor_trigger}; dominant_rpki={dominant_status}; "
        f"valid_share={valid_share:.4f}; invalid_share={invalid_share:.4f}; "
        f"unknown_share={unknown_share:.4f}; component={component_class}"
    )

    severe_conflict = (
        component_class == "mixed_conflicting"
        or (dominant_status == "valid" and invalid_share >= 0.20)
        or (dominant_status in INVALID_STATUSES and valid_share >= 0.50 and invalid_share < 0.30)
    )
    if severe_conflict:
        conflict_reason = "member/component RPKI statuses are materially mixed or contradict the dominant pair"
        return {
            "verifier_verdict_vrp": "evidence_conflict",
            "verifier_confidence_cap": 0.55,
            "confidence_cap_reason": "evidence conflict cap",
            "abstain_reason": "",
            "conflict_reason": conflict_reason,
            "evidence_strength_summary": evidence_summary,
            "learning_eligibility": "conflict_class",
            "safe_positive_candidate_flag": False,
            "safe_negative_candidate_flag": False,
            "topk_review_bucket": "conflict_review",
        }

    if unavailable_share >= 0.99:
        return {
            "verifier_verdict_vrp": "external_evidence_unavailable",
            "verifier_confidence_cap": 0.45,
            "confidence_cap_reason": "external evidence unavailable cap",
            "abstain_reason": "",
            "conflict_reason": "",
            "evidence_strength_summary": evidence_summary,
            "learning_eligibility": "ranking_only",
            "safe_positive_candidate_flag": False,
            "safe_negative_candidate_flag": False,
            "topk_review_bucket": "evidence_unavailable_review",
        }

    if should_split:
        abstain_reason = "incident is component-mixed and should be split before a safe incident-level verdict"
        return {
            "verifier_verdict_vrp": "abstain",
            "verifier_confidence_cap": 0.50,
            "confidence_cap_reason": "component split required",
            "abstain_reason": abstain_reason,
            "conflict_reason": "",
            "evidence_strength_summary": evidence_summary,
            "learning_eligibility": "abstain_class",
            "safe_positive_candidate_flag": False,
            "safe_negative_candidate_flag": False,
            "topk_review_bucket": "component_split_review",
        }

    invalid_not_edge = invalid_count >= 3 and (invalid_share >= 0.10 or invalid_core_share >= 0.60)
    purity_ok = component_class in {"pure_dominant", "mostly_dominant", "mixed_but_core_suspicious"}
    if strong_monitor_trigger and invalid_not_edge and purity_ok:
        # R-2B intentionally does not emit strongly_supported_suspicious. VRP is
        # origin authorization evidence and needs path/legality corroboration.
        return {
            "verifier_verdict_vrp": "evidence_supported_suspicious",
            "verifier_confidence_cap": 0.75,
            "confidence_cap_reason": "monitor trigger plus aligned RPKI invalid component evidence",
            "abstain_reason": "",
            "conflict_reason": "",
            "evidence_strength_summary": evidence_summary,
            "learning_eligibility": "positive_candidate",
            "safe_positive_candidate_flag": True,
            "safe_negative_candidate_flag": False,
            "topk_review_bucket": "evidence_supported_topk_candidate",
        }

    background_like = queue in {"low_priority_background", "background_like_review"} and high_share < 0.05
    if background_like and invalid_share < 0.05:
        return {
            "verifier_verdict_vrp": "background_like_but_unconfirmed",
            "verifier_confidence_cap": 0.50,
            "confidence_cap_reason": "background-like but not normal label",
            "abstain_reason": "",
            "conflict_reason": "",
            "evidence_strength_summary": evidence_summary,
            "learning_eligibility": "ranking_only",
            "safe_positive_candidate_flag": False,
            "safe_negative_candidate_flag": False,
            "topk_review_bucket": "background_sampling",
        }

    if monitor_trigger:
        return {
            "verifier_verdict_vrp": "evidence_insufficient",
            "verifier_confidence_cap": 0.50,
            "confidence_cap_reason": "monitor trigger without sufficient consistent external support",
            "abstain_reason": "",
            "conflict_reason": "",
            "evidence_strength_summary": evidence_summary,
            "learning_eligibility": "ranking_only",
            "safe_positive_candidate_flag": False,
            "safe_negative_candidate_flag": False,
            "topk_review_bucket": "evidence_gap_review",
        }

    return {
        "verifier_verdict_vrp": "background_like_but_unconfirmed",
        "verifier_confidence_cap": 0.45,
        "confidence_cap_reason": "no strong monitor trigger and no sufficient suspicious evidence",
        "abstain_reason": "",
        "conflict_reason": "",
        "evidence_strength_summary": evidence_summary,
        "learning_eligibility": "ranking_only",
        "safe_positive_candidate_flag": False,
        "safe_negative_candidate_flag": False,
        "topk_review_bucket": "background_sampling",
    }


def apply_verdicts(df: pd.DataFrame) -> pd.DataFrame:
    verdict_df = pd.DataFrame([verdict_for_row(row) for _, row in df.iterrows()], index=df.index)
    out = pd.concat([df, verdict_df], axis=1)
    out["triage_score_vrp"] = (
        out["incident_score"].map(lambda x: safe_float(x))
        + out["rpki_invalid_share"].map(lambda x: safe_float(x)) * 25.0
        + out["high_share"].map(lambda x: safe_float(x)) * 10.0
        + out["collector_union_count"].map(lambda x: min(safe_float(x), 10.0)) * 0.5
        - out["rpki_status_entropy"].map(lambda x: safe_float(x)) * 4.0
        - out["should_split_incident_flag"].astype(bool).astype(float) * 10.0
    )
    return out


def hard_safety_violations(df: pd.DataFrame) -> list[str]:
    violations: list[str] = []
    if "confirmed_attack" in " ".join(map(str, df.columns)):
        violations.append("forbidden confirmed_attack column detected")
    if "confirmed_benign" in " ".join(map(str, df.columns)):
        violations.append("forbidden confirmed_benign column detected")
    strong_monitor_trigger = (
        (df["high_count"].map(lambda x: safe_float(x)) > 0)
        | df["verification_queue"].isin(["high_confidence_candidate", "patternB_path_abnormal_verification"])
    )
    invalid_only = df[
        (df["verifier_verdict_vrp"].isin(["evidence_supported_suspicious", "strongly_supported_suspicious"]))
        & (~strong_monitor_trigger)
    ]
    if len(invalid_only):
        violations.append(f"{len(invalid_only)} suspicious verdict rows lack monitor-side high support")
    if (df["safe_negative_candidate_flag"] == True).any():  # noqa: E712
        violations.append("safe_negative_candidate_flag must remain false")
    unexpected = set(df["verifier_verdict_vrp"].dropna().unique()) - R1_VERDICTS
    if unexpected:
        violations.append(f"verdict outside R-1 set: {sorted(unexpected)}")
    return violations


def write_outputs(args: argparse.Namespace, table: pd.DataFrame, warnings: list[str]) -> None:
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    table_path = out_dir / "r2b_vrp_incident_verifier_table.parquet"
    table.to_parquet(table_path, index=False)
    table.to_csv(out_dir / "r2b_vrp_incident_verifier_table.csv", index=False)

    verdict_dist = table["verifier_verdict_vrp"].value_counts().rename_axis("verdict").reset_index(name="incident_count")
    verdict_dist.to_csv(out_dir / "r2b_vrp_verdict_distribution.csv", index=False)

    dominant_status_dist = (
        table["dominant_pair_rpki_status"].fillna("unavailable").value_counts().rename_axis("rpki_status").reset_index(name="incident_count")
    )
    dominant_status_dist.to_csv(out_dir / "r2b_rpki_incident_status_distribution.csv", index=False)

    purity_dist = (
        table["component_purity_class"].value_counts().rename_axis("component_purity_class").reset_index(name="incident_count")
    )
    purity_dist.to_csv(out_dir / "r2b_component_purity_distribution.csv", index=False)

    table[table["mixed_rpki_status_flag"] | table["should_split_incident_flag"]].sort_values(
        ["should_split_incident_flag", "rpki_status_entropy", "member_count"], ascending=[False, False, False]
    ).head(1000).to_csv(out_dir / "r2b_mixed_incident_cases.csv", index=False)

    table[table["verifier_verdict_vrp"] == "evidence_supported_suspicious"].sort_values(
        "triage_score_vrp", ascending=False
    ).head(1000).to_csv(out_dir / "r2b_evidence_supported_candidates.csv", index=False)

    table[table["verifier_verdict_vrp"] == "evidence_conflict"].sort_values(
        "triage_score_vrp", ascending=False
    ).head(1000).to_csv(out_dir / "r2b_conflict_cases.csv", index=False)

    table[table["verifier_verdict_vrp"] == "abstain"].sort_values(
        "triage_score_vrp", ascending=False
    ).head(1000).to_csv(out_dir / "r2b_abstain_cases.csv", index=False)

    topk = table.sort_values("triage_score_vrp", ascending=False).head(500).copy()
    topk.to_csv(out_dir / "r2b_topk_review_candidates.csv", index=False)

    legacy_p1_p2 = int(table["calibrated_incident_priority"].isin(["P1_high", "P2_review"]).sum())
    evidence_supported = int((table["verifier_verdict_vrp"] == "evidence_supported_suspicious").sum())
    conflict_count = int((table["verifier_verdict_vrp"] == "evidence_conflict").sum())
    abstain_count = int((table["verifier_verdict_vrp"] == "abstain").sum())
    candidate_review_count = evidence_supported + conflict_count + abstain_count
    unsupported_proxy = 1.0 - (candidate_review_count / legacy_p1_p2) if legacy_p1_p2 else 0.0
    burden_rows = []
    for k in [50, 100, 500]:
        subset = table.sort_values("triage_score_vrp", ascending=False).head(k)
        density = float((subset["verifier_verdict_vrp"] == "evidence_supported_suspicious").mean()) if len(subset) else 0.0
        burden_rows.append(
            {
                "k": k,
                "topk_candidate_count": int(len(subset)),
                "evidence_supported_density_in_topk": density,
            }
        )
    burden_rows.append(
        {
            "k": "legacy_p1_p2",
            "topk_candidate_count": legacy_p1_p2,
            "evidence_supported_density_in_topk": evidence_supported / legacy_p1_p2 if legacy_p1_p2 else 0.0,
        }
    )
    burden = pd.DataFrame(burden_rows)
    burden["legacy_p1_p2_count"] = legacy_p1_p2
    burden["vrp_evidence_supported_count"] = evidence_supported
    burden["vrp_conflict_count"] = conflict_count
    burden["abstain_count"] = abstain_count
    burden["unsupported_alert_reduction_proxy"] = unsupported_proxy
    burden.to_csv(out_dir / "r2b_human_burden_proxy.csv", index=False)

    safety = hard_safety_violations(table)
    summary = {
        "run_id": args.run_id,
        "run_date": args.run_date,
        "full_run": bool(args.full_run),
        "sample_rows": int(args.sample_rows or 0),
        "total_incidents": int(table["incident_id"].nunique()),
        "processed_incidents": int(len(table)),
        "dominant_pair_status_distribution": distribution(table["dominant_pair_rpki_status"]),
        "member_status_distribution": {
            "valid": int(table["rpki_valid_member_count"].sum()),
            "invalid_asn": int(table["rpki_invalid_asn_member_count"].sum()),
            "invalid_length": int(table["rpki_invalid_length_member_count"].sum()),
            "unknown": int(table["rpki_unknown_member_count"].sum()),
            "unavailable": int(table["rpki_unavailable_member_count"].sum()),
        },
        "component_purity_distribution": distribution(table["component_purity_class"]),
        "verdict_distribution": distribution(table["verifier_verdict_vrp"]),
        "evidence_supported_count": evidence_supported,
        "conflict_count": conflict_count,
        "insufficient_count": int((table["verifier_verdict_vrp"] == "evidence_insufficient").sum()),
        "background_like_count": int((table["verifier_verdict_vrp"] == "background_like_but_unconfirmed").sum()),
        "abstain_count": abstain_count,
        "external_unavailable_count": int((table["verifier_verdict_vrp"] == "external_evidence_unavailable").sum()),
        "strong_supported_count": int((table["verifier_verdict_vrp"] == "strongly_supported_suspicious").sum()),
        "hard_safety_violations": safety,
        "mixed_incident_count": int(table["mixed_rpki_status_flag"].sum()),
        "should_split_incident_count": int(table["should_split_incident_flag"].sum()),
        "legacy_p1_p2_count": legacy_p1_p2,
        "human_burden_proxy": {
            "candidate_review_count_evidence_conflict_abstain": candidate_review_count,
            "unsupported_alert_reduction_proxy": unsupported_proxy,
            "top50_evidence_supported_density": float(burden.loc[burden["k"] == 50, "evidence_supported_density_in_topk"].iloc[0]),
            "top100_evidence_supported_density": float(burden.loc[burden["k"] == 100, "evidence_supported_density_in_topk"].iloc[0]),
            "top500_evidence_supported_density": float(burden.loc[burden["k"] == 500, "evidence_supported_density_in_topk"].iloc[0]),
        },
        "can_enter_r2c": len(safety) == 0,
        "can_enter_learning_layer": False,
        "recommended_next_step": "R-2C path evidence branch, with R-3 poisoning benchmark design and L1 component-aware learner design in parallel documents",
        "warnings": warnings,
        "status": "completed" if not safety else "completed_with_safety_warnings",
    }
    write_json(out_dir / "r2b_vrp_verifier_summary.json", summary)
    write_report(out_dir / "r2b_vrp_smoke_report.md", summary)


def write_report(path: Path, summary: dict[str, Any]) -> None:
    verdict = summary["verdict_distribution"]
    purity = summary["component_purity_distribution"]
    status = summary["dominant_pair_status_distribution"]
    member_status = summary["member_status_distribution"]
    lines = [
        "# R-2B VRP-Aware Verifier Smoke Report",
        "",
        f"Run id: `{summary['run_id']}`",
        f"Run date: `{summary['run_date']}`",
        f"Status: `{summary['status']}`",
        "",
        "## 1. Did VRP Evidence Join Back to the Verifier?",
        "",
        "Yes. R-2B consumed the aligned R-2B-P0b RPKI lookup table and joined it back to incident-level S3-D queues.",
        "It preserves both dominant prefix-origin status and member/component status distribution.",
        "",
        "## 2. External Evidence Unavailable",
        "",
        f"`external_evidence_unavailable={summary['external_unavailable_count']}` in the VRP-aware verifier output.",
        "This is expected to drop relative to R-2A because RPKI/VRP is now aligned for the fixed run. Any remaining unavailable status comes from join gaps or member pairs absent from the R-2B-P0b lookup map.",
        "",
        "## 3. RPKI Status Distribution",
        "",
        "Dominant pair status:",
        "",
        *[f"- `{k}`: `{v}`" for k, v in sorted(status.items())],
        "",
        "Member/component status counts:",
        "",
        *[f"- `{k}`: `{v}`" for k, v in sorted(member_status.items())],
        "",
        "RPKI status is evidence only: valid is not benign, invalid is not confirmed attack, and unknown is not normal.",
        "",
        "## 4. Incident Purity / Component Audit",
        "",
        *[f"- `{k}`: `{v}`" for k, v in sorted(purity.items())],
        "",
        f"Mixed incidents: `{summary['mixed_incident_count']}`",
        f"Should-split incidents: `{summary['should_split_incident_count']}`",
        "",
        "Mixed incidents are not forced into suspicious or background verdicts. They are routed to conflict or abstain where component evidence is not safe enough.",
        "",
        "## 5. Verdict Distribution",
        "",
        *[f"- `{k}`: `{v}`" for k, v in sorted(verdict.items())],
        "",
        f"Evidence-supported suspicious count: `{summary['evidence_supported_count']}`",
        f"Strongly supported suspicious count: `{summary['strong_supported_count']}`",
        "",
        "R-2B intentionally keeps `strongly_supported_suspicious` at zero unless future path/legality evidence corroborates RPKI evidence. RPKI invalid alone is insufficient.",
        "",
        "## 6. Hard Safety Violations",
        "",
        f"Hard safety violations: `{len(summary['hard_safety_violations'])}`",
        "",
        *[f"- {v}" for v in summary["hard_safety_violations"]],
        "",
        "## 7. Human Burden Proxy",
        "",
        f"Legacy P1/P2 incidents: `{summary['legacy_p1_p2_count']}`",
        f"Evidence/conflict/abstain candidate review count: `{summary['human_burden_proxy']['candidate_review_count_evidence_conflict_abstain']}`",
        f"Unsupported alert reduction proxy: `{summary['human_burden_proxy']['unsupported_alert_reduction_proxy']:.6f}`",
        f"Top-50 evidence-supported density: `{summary['human_burden_proxy']['top50_evidence_supported_density']:.6f}`",
        f"Top-100 evidence-supported density: `{summary['human_burden_proxy']['top100_evidence_supported_density']:.6f}`",
        f"Top-500 evidence-supported density: `{summary['human_burden_proxy']['top500_evidence_supported_density']:.6f}`",
        "",
        "This is a smoke-level burden proxy, not a final human-burden experiment.",
        "",
        "## 8. Next Step",
        "",
        f"Can enter R-2C: `{summary['can_enter_r2c']}`",
        f"Can enter learning layer: `{summary['can_enter_learning_layer']}`",
        "",
        "Recommended order:",
        "",
        "1. R-2C path evidence branch / route-leak legality refinement.",
        "2. R-3 poisoning benchmark early design.",
        "3. L1 component-aware semantic learner design.",
        "",
        "Learning can be designed now, but formal training remains blocked until verifier-supported targets and robustness settings are stronger.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    warnings: list[str] = []

    base = load_incident_base(args, warnings)
    incident_lookup, pair_lookup = load_rpki_lookup(args.rpki_lookup_file, warnings)
    component = component_audit(args, base, pair_lookup, warnings)

    table = base.merge(incident_lookup, on="incident_id", how="left")
    table = table.merge(component.drop(columns=["member_count"], errors="ignore"), on="incident_id", how="left")

    table["dominant_pair_rpki_status"] = table["dominant_pair_rpki_status"].fillna("unavailable")
    table["dominant_pair_rpki_evidence_state"] = table["dominant_pair_rpki_evidence_state"].fillna("unavailable")
    table["dominant_pair_target_id"] = table["dominant_pair_target_id"].fillna("")

    numeric_defaults = [
        "rpki_valid_member_count",
        "rpki_invalid_asn_member_count",
        "rpki_invalid_length_member_count",
        "rpki_unknown_member_count",
        "rpki_unavailable_member_count",
        "rpki_invalid_total_count",
        "rpki_valid_share",
        "rpki_invalid_share",
        "rpki_unknown_share",
        "rpki_unavailable_share",
        "dominant_prefix_origin_share",
        "rpki_status_entropy",
        "invalid_core_share",
        "invalid_edge_share",
        "suspicious_component_member_count",
        "suspicious_component_share",
    ]
    for col in numeric_defaults:
        if col not in table.columns:
            table[col] = 0
        table[col] = table[col].fillna(0)
    for col in ["mixed_rpki_status_flag", "should_split_incident_flag"]:
        if col not in table.columns:
            table[col] = False
        table[col] = table[col].fillna(False).astype(bool)
    if "component_purity_class" not in table.columns:
        table["component_purity_class"] = "insufficient_component_signal"

    if "high_share" not in table.columns:
        denominator = table["member_count"].where(table["member_count"] > 0, 1)
        table["high_share"] = table["high_count"] / denominator

    table = apply_verdicts(table)
    write_outputs(args, table, warnings)

    summary_path = Path(args.output_dir) / "r2b_vrp_verifier_summary.json"
    print(summary_path)


if __name__ == "__main__":
    main()
